---
title: "Cardiovascular Disease Prediction"
author: "Duane Edmonds"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE
)
library(tidyverse)
library(tidymodels)
library(magrittr)
```

```{r data_clean, include = FALSE}
patients <- readr::read_csv(
  "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data",
  col_names = c(
                "age",
                "sex", # male (1),female (0)
                "c_pain", # chest pain 
                              #   typical angina (1)
                              #   atypical angina (2)
                              #   non-anginal pain (3)
                              #   asymptomatic (4)
                "b_press", # resting blood pressure upon admission [mmHg]
                "choles", # serum cholesterol [mg/dl]
                "b_sugar", # fasting blood sugar
                           #   <= 120 mg/dl (0)
                           #   > 120 mg/dl (1)
                "ecg", # resting electrocardiograph results  
                       #   normal (0)
                       #   ST-T wave abnormality (1)
                       #   left ventricular hypertrophy (2)
                "h_rate", # maximum heart rate
                "angina", # exercise induced angina; true (1), false (0)    
                "s_dep", # ST depression induced by exercise relative to rest
                "s_slope", # peak exercise ST element slope; up (1), flat(2), down (3)
                "b_vess", # number of major vessels (0-3) colored by fluoroscope
                "thal", # normal (3), 6 = fixed defect (6), 7 = reversible defect (7)
                "diag" # diagnosis of heart disease (angiographic disease status)
                ),
  na = c("?")
)


# remove observations with NAs (only 6 in data set)
patients <- patients %>%
  drop_na()

patients <- patients %>% 
  mutate(
    diag = as.factor(ifelse(diag == 0, "NOT_DISEASED", "DISEASED"))
  )

knitr::kable(patients)
```

### Correlation matrix

```{r correlation}
knitr::kable(round(cor(patients %>% select(-diag)), digits = 3))
```

### Pre-processing

```{r pre_process, include = FALSE}
set.seed(618)

# perform training-test data split
data_split <- patients %>% 
  initial_split(
    prop = 0.8
  )
train_data <- training(data_split)
test_data <- testing(data_split)

# prepare recipe steps
recipe <- train_data %>% 
  recipe(diag ~ .) %>% 
  step_normalize(
    all_numeric()
  ) %>% 
  prep()

# extract pre-processed training data (juice)
processed_train_data <- juice(recipe)

# execute pre-processing steps on test data (bake)
processed_test_data <- recipe %>% 
  bake(test_data)
```

### Supervised learning

#### Gradient Boost

```{r train, include = FALSE}
model <- boost_tree(
           trees = 200,
           mode = "classification",
           learn_rate = 0.3,
           tree_depth = 4
         ) %>%
  set_engine("xgboost") %>%
  fit(diag ~ ., data = processed_train_data)
```

```{r predict, include = FALSE}
prediction_matrix <- model %>%
  predict(processed_test_data) %>%
  bind_cols(processed_test_data)
```

```{r accuracy, include = FALSE}
model_accuracy <- prediction_matrix %>%
  metrics(truth = diag, estimate = .pred_class) %$%
  .estimate[1]

model_accuracy
```

The model accuracy is `r format(model_accuracy, digits = 5)`.

```{r confusion, out.width = "70%"}
cm <- model %>%
  predict(processed_test_data) %>%
  bind_cols(processed_test_data) %>%
  conf_mat(truth = diag, estimate = .pred_class)

autoplot(cm, type = "heatmap")
```

#### k-Nearest Neighbors

```{r train_knn, include = FALSE}
model_knn <- nearest_neighbor(
               neighbors = 5,
               mode = "classification",
               dist_power = 1,
               weight_func = "optimal"
             ) %>%
  set_engine("kknn") %>%
  fit(diag ~ ., data = processed_train_data)
```

```{r predict_knn, include = FALSE}
knn_accuracy <- model_knn %>%
  predict(processed_test_data) %>%
  bind_cols(processed_test_data) %>%
  metrics(truth = diag, estimate = .pred_class) %$%
  .estimate[1]

knn_accuracy
```

The model accuracy is `r format(knn_accuracy, digits = 5)`.

```{r knn_confusion, out.width = "70%"}
cm_knn <- model_knn %>%
  predict(processed_test_data) %>%
  bind_cols(processed_test_data) %>%
  conf_mat(truth = diag, estimate = .pred_class)

autoplot(cm_knn, type = "heatmap")
```
